export const SERVER_URL =
  process.env.NEXT_PUBLIC_SERVER_URL ||
  process.env.NEXT_PUBLIC_VERCEL_URL ||
  'http://localhost:3000';

export const dockUrl = process.env.NEXT_PUBLIC_DOCK_API_URL;
export const BANK_NAME = 'Verifi Bank';
export const HOTEL_NAME = 'Dockside Resorts';

export default {
  SERVER_URL,
  BANK_NAME,
  HOTEL_NAME,
};

export const PROOFT_TEMPLATES_IDS = {
  //INTO THE LOAN PAGE CHECKS BANK IDENTITY, BIOMETRICS & CREDITSCORE
  LOAN_PROOF: process.env.NEXT_PUBLIC_QUOTIENT_LOAN_PROOF_TEMPLATE_ID,
  //BIOMETRIC ENROLLMET & BIOMETRICAL CHECK
  FORSUR_BIOMETRICS: process.env.NEXT_PUBLIC_FORSUR_PROOF_TEMPLATE_ID,
  //BANK IDENTITY & BIOMETRICS
  URBANSCAPE_BANKBIO: process.env.NEXT_PUBLIC_URBANSCAPE_BANKBIO_TEMPLATE_ID,
  //CREDITSCORE ONLY
  URBANSCAPE_CREDITSCORE: process.env.NEXT_PUBLIC_URBANSCAPE_CREDITSCORE_TEMPLATE_ID,
  //BANK IDENTITY & BIOMETRICS
  BANK_IDENDITY: process.env.NEXT_PUBLIC_BANK_IDENDITY_TEMPLATE_ID
}