name: format-check

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - master
      - main

# Auto cancels previous running CI jobs in this PR on each new commit
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format-check:
    runs-on: ubuntu-latest-m
    env:
      NODE_VERSION: 19.x

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Format check
        run: npm run format-check
